[package]
name = "burg_simple_http"
version = "0.1.0"
edition = "2021"

[dependencies]
#hex-literal = "0.4.1"
maud = "0.26.0"
rand = "0.8.5"
#rustc-serialize = "0.3.25"
#sha1 = "0.10.6"
tiny_http = "0.12.0"
